---
- hosts: localhost
  vars:
    hostname: "vcenter.ansible.local"
    esxihostname: "esxi.ansible.local"
    username: "administrator@vsphere.local"
    password: "Passw0rd!"
    nfs_user: "user"
    portgroup_name: "webserver"
    vlan_id: "1"

  tasks:
  - name: Add NFS Storage ESXi
    vmware_host_datastore:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      esxi_hostname: "{{ esxihostname }}"
      datastore_name: "datastore_{{ nfs_user }}"
      datastore_type: "nfs"
      nfs_server: "ansible.ansible.local"
      nfs_path: "/storage/{{ nfs_user }}"
      nfs_ro: "no"
      state: "present"
      validate_certs: "False"
    delegate_to: "localhost"

  - name: Add a PortGroup to VMware vSwitch
    vmware_portgroup:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      switch_name: "vSwitch0"
      esxi_hostname: "{{ esxihostname }}"
      portgroup_name: "{{ portgroup_name }}"
    delegate_to: localhost

  - name: Clone Centos 8 to webserver
    vmware_guest:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "False"
      name: "webserver"
      template: "Temp_Centos8"
      datacenter: "Datacenter"
      folder: "/"
      state: "poweredon"
      hardware:
        memory_mb: "1024"
        num_cpus: "1"
      disk:
      - size_gb: "16"
        type: "thin"
        datastore: "datastore1"
      - size_gb: "2"
        type: "thin"
        datastore: "datastore_{{ nfs_user }}"
      networks:
      - name: "{{ portgroup_name }}"
        connected: true
      wait_for_ip_address: "yes"
    register: "webserver"
  - name: Set Fact webserver_ip_fact
    set_fact:
     webserver_ip_fact: "{{ webserver.instance.ipv4 }}"

  - name: IP address info
    debug:
      msg: "{{ webserver_ip_fact }}"

  - name: Add ansibleserver to ssh known_hosts
    shell: "ssh-keyscan -t ecdsa {{ webserver_ip_fact }}  >> /home/{{ ansible_user_id }}/.ssh/known_hosts"

  - name: Create a category
    vmware_category:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      category_name: "ansible_managed"
      category_description: "Category for Ansible"
      category_cardinality: 'multiple'
      state: present
    register: category

  - name: Create a tag
    vmware_tag:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      category_id: "{{ category.category_results.category_id }}"
      tag_name: "tag_webserver"
      tag_description: "Web Server"
      state: present
    delegate_to: localhost

  - name: Create a tag
    vmware_tag:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      category_id: "{{ category.category_results.category_id }}"
      tag_name: "tag_dbserver"
      tag_description: "Database Server"
      state: present
    delegate_to: localhost

  - name: Add tags to webserver
    vmware_tag_manager:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tag_names:
        - "tag_webserver"
      object_name: "webserver"
      object_type: VirtualMachine
      state: add
    delegate_to: localhost
